### ISSUE TITLE
Couldn't resolve Onshape dependency

### ISSUE THREAD

**Issue by eak24** [harmanpa/onshape-tests#1]
Hi @harmanpa when I run the code as it currently stands, seems like the dependency is pointing to the wrong repo, eg: https://github.com/harmanpa/onshape-tests/blob/master/pom.xml#L42 . It should be pointing here:

```
	<dependency>
	    <groupId>com.github.onshape-public</groupId>
	    <artifactId>java-client</artifactId>
	    <version>v1.94.23174.ae43e3d58936</version>
	</dependency>
```

**Comment by harmanpa** [comment]
If you build java-client locally it has the groupId of com.onshape, so it was pointing at a dev version on my machine. I guess I could use Maven profiles to switch between them, I was just being lazy and commenting one out :-)

**Comment by eak24** [comment]
I see! I got it working on my machine, so I'm all set here. Thanks!
